<center>
<img src="https://habrastorage.org/files/fd4/502/43d/fd450243dd604b81b9713213a247aa20.jpg">
    
## [mlcourse.ai](mlcourse.ai) – Open Machine Learning Course 

<center>Author: [Yury Kashnitskiy](http://yorko.github.io) <br>
Translated and edited by [Sergey Isaev](https://www.linkedin.com/in/isvforall/), [Artem Trunov](https://www.linkedin.com/in/datamove/), [Anastasia Manokhina](https://www.linkedin.com/in/anastasiamanokhina/), and [Yuanyuan Pao](https://www.linkedin.com/in/yuanyuanpao/) <br>All content is distributed under the [Creative Commons CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) license.

# <center> Assignment #1 (demo)
## <center>  Exploratory data analysis with Pandas

**In this task you should use Pandas to answer a few questions about the [Adult](https://archive.ics.uci.edu/ml/datasets/Adult) dataset. (You don't have to download the data – it's already here). Choose the answers in the [web-form](https://docs.google.com/forms/d/1uY7MpI2trKx6FLWZte0uVh3ULV4Cm_tDud0VDFGCOKg). This is a demo version of an assignment, so by submitting the form, you'll see a link to the solution .ipynb file.**

Unique values of all features (for more information, please see the links above):
- `age`: continuous.
- `workclass`: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
- `fnlwgt`: continuous.
- `education`: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
- `education-num`: continuous.
- `marital-status`: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
- `occupation`: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
- `relationship`: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
- `race`: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
- `sex`: Female, Male.
- `capital-gain`: continuous.
- `capital-loss`: continuous.
- `hours-per-week`: continuous.
- `native-country`: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.   
- `salary`: >50K,<=50K

In [3]:
import pandas as pd

In [10]:
df = pd.read_csv('data/adult.data.csv')
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  str
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  str
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  str
 6   occupation      32561 non-null  str
 7   relationship    32561 non-null  str
 8   race            32561 non-null  str
 9   sex             32561 non-null  str
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  32561 non-null  str
 14  salary          32561 non-null  str
dtypes: int64(6), str(9)
memory usage: 3.7 MB

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. How many men and women (*sex* feature) are represented in this dataset?**

In [14]:
# You code here
df['sex'].value_counts()

sex
Male      21790
Female    10771
Name: count, dtype: int64

**2. What is the average age (*age* feature) of women?**

In [ ]:
# You code here
df[df['sex'] == 'Female']['age'].mean()

np.float64(36.85823043357163)

**3. What is the percentage of German citizens (*native-country* feature)?**

In [25]:
# You code here
df['native-country'].value_counts(normalize = True)

native-country
United-States                 0.895857
Mexico                        0.019748
?                             0.017905
Philippines                   0.006081
Germany                       0.004207
Canada                        0.003716
Puerto-Rico                   0.003501
El-Salvador                   0.003255
India                         0.003071
Cuba                          0.002918
England                       0.002764
Jamaica                       0.002488
South                         0.002457
China                         0.002303
Italy                         0.002242
Dominican-Republic            0.002150
Vietnam                       0.002058
Guatemala                     0.001966
Japan                         0.001904
Poland                        0.001843
Columbia                      0.001812
Taiwan                        0.001566
Haiti                         0.001351
Iran                          0.001321
Portugal                      0.001136
Nicaragua                     0.001044
Peru                          0.000952
France                        0.000891
Greece                        0.000891
Ecuador                       0.000860
Ireland                       0.000737
Hong                          0.000614
Cambodia                      0.000584
Trinadad&Tobago               0.000584
Thailand                      0.000553
Laos                          0.000553
Yugoslavia                    0.000491
Outlying-US(Guam-USVI-etc)    0.000430
Honduras                      0.000399
Hungary                       0.000399
Scotland                      0.000369
Holand-Netherlands            0.000031
Name: proportion, dtype: float64

** 4-5. What are the mean and standard deviation of age for those who earn more than 50K per year (*salary* feature) and those who earn less than 50K per year? **

In [28]:
# You code here
df.groupby('salary')['age'].agg(['mean', 'std'])

             mean        std
salary
<=50K   36.783738  14.020088
>50K    44.249841  10.519028

**6. Is it true that people who earn more than 50K have at least high school education? (*education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* or *Doctorate* feature)**

In [ ]:
# You code here
allowed = ['Bachelors', 'Prof-school', 'Assoc-acdm', 'Assoc-voc', 'Masters', 'Doctorate']

df[df['salary'] == '>50K']['education'].isin(allowed).all()

np.False_

**7. Display age statistics for each race (*race* feature) and each gender (*sex* feature). Use *groupby()* and *describe()*. Find the maximum age of men of *Amer-Indian-Eskimo* race.**

In [41]:
# You code here
from IPython.display import display

display(df.groupby('race')['age'].describe())
display(df.groupby('sex')['age'].describe())

df[df['race'] == 'Amer-Indian-Eskimo']['age'].max()

,count,mean,std,min,25%,50%,75%,max
race,,,,,,,,
Amer-Indian-Eskimo,311.0,37.173633,12.447130,17.0,28.0,35.0,45.5,82.0
Asian-Pac-Islander,1039.0,37.746872,12.825133,17.0,28.0,36.0,45.0,90.0
Black,3124.0,37.767926,12.759290,17.0,28.0,36.0,46.0,90.0
Other,271.0,33.457565,11.538865,17.0,25.0,31.0,41.0,77.0
White,27816.0,38.769881,13.782306,17.0,28.0,37.0,48.0,90.0

          count       mean        std   min   25%   50%   75%   max
sex
Female  10771.0  36.858230  14.013697  17.0  25.0  35.0  46.0  90.0
Male    21790.0  39.433547  13.370630  17.0  29.0  38.0  48.0  90.0

np.int64(82)

**8. Among whom is the proportion of those who earn a lot (>50K) greater: married or single men (*marital-status* feature)? Consider as married those who have a *marital-status* starting with *Married* (Married-civ-spouse, Married-spouse-absent or Married-AF-spouse), the rest are considered bachelors.**

In [65]:
# You code here
df['marital-status'].unique()

<StringArray>
[        'Never-married',    'Married-civ-spouse',              'Divorced',
 'Married-spouse-absent',             'Separated',     'Married-AF-spouse',
               'Widowed']
Length: 7, dtype: str

In [86]:
men = df[df['sex'] == 'Male']

pd.crosstab(
    men['marital-status'].str.startswith('Married'),
    men['salary'],
    normalize='index'
)

salary             <=50K      >50K
marital-status
False           0.915505  0.084495
True            0.559486  0.440514

**9. What is the maximum number of hours a person works per week (*hours-per-week* feature)? How many people work such a number of hours, and what is the percentage of those who earn a lot (>50K) among them?**

In [68]:
# You code here
df['hours-per-week'].max()

np.int64(99)

In [69]:
df[df['hours-per-week'] == 99].shape[0]

85

In [76]:
df.loc[df['hours-per-week'] == 99, 'salary'].value_counts(normalize=True)

salary
<=50K    0.705882
>50K     0.294118
Name: proportion, dtype: float64

**10. Count the average time of work (*hours-per-week*) for those who earn a little and a lot (*salary*) for each country (*native-country*). What will these be for Japan?**

In [85]:
# You code here
pd.crosstab(
    index=df['native-country'],
    columns=df['salary'],
    values=df['hours-per-week'],
    aggfunc='mean'
).round(2)

salary                      <=50K   >50K
native-country
?                           40.16  45.55
Cambodia                    41.42  40.00
Canada                      37.91  45.64
China                       37.38  38.90
Columbia                    38.68  50.00
Cuba                        37.99  42.44
Dominican-Republic          42.34  47.00
Ecuador                     38.04  48.75
El-Salvador                 36.03  45.00
England                     40.48  44.53
France                      41.06  50.75
Germany                     39.14  44.98
Greece                      41.81  50.62
Guatemala                   39.36  36.67
Haiti                       36.33  42.75
Holand-Netherlands          40.00    NaN
Honduras                    34.33  60.00
Hong                        39.14  45.00
Hungary                     31.30  50.00
India                       38.23  46.48
Iran                        41.44  47.50
Ireland                     40.95  48.00
Italy                       39.62  45.40
Jamaica                     38.24  41.10
Japan                       41.00  47.96
Laos                        40.38  40.00
Mexico                      40.00  46.58
Nicaragua                   36.09  37.50
Outlying-US(Guam-USVI-etc)  41.86    NaN
Peru                        35.07  40.00
Philippines                 38.07  43.03
Poland                      38.17  39.00
Portugal                    41.94  41.50
Puerto-Rico                 38.47  39.42
Scotland                    39.44  46.67
South                       40.16  51.44
Taiwan                      33.77  46.80
Thailand                    42.87  58.33
Trinadad&Tobago             37.06  40.00
United-States               38.80  45.51
Vietnam                     37.19  39.20
Yugoslavia                  41.60  49.50